version: "3"

services:
  dbmongo:
    image: mongo:3.4
  api:
    image : node:8.1
    depends_on:
      - dbmongo
    volumes:
      - "./api:/api"
    command: bash -c "cd /api && npm install && npm run start"
    
  app:
    build: ./app
    volumes:
      - ./app:/app
    depends_on:
      - api
    ports:
      - "80:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    links:
      - api